In [1]:
import nltk
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Data = pd.read_csv("D:/Imarticus/DSP17/Assignments/NLP/SMSSpamCollection", sep = '\t', header = None)

In [2]:
Data.head()

0                                                  1
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
Data.columns = ['label','message']
Data.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
Data.describe()

label                 message
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [5]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [6]:
def remove_punct(txt):
    text = [wrd for wrd in txt if wrd not in string.punctuation]
    return ''.join(text)

In [7]:
Data['rm_punct'] = Data['message'].apply(lambda x : remove_punct(x))
Data.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                            rm_punct  
0  Go until jurong point crazy Available only in ...  
1                            Ok lar Joking wif u oni  
2  Free entry in 2 a wkly comp to win FA Cup fina...  
3        U dun say so early hor U c already then say  
4  Nah I dont think he goes to usf he lives aroun...

In [8]:
import re

def tokenize(text):
    tokens = re.split('\W+', text)
    return tokens

In [9]:
Data['Tokens'] = Data['rm_punct'].apply(lambda x: tokenize(x))
Data.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                            rm_punct  \
0  Go until jurong point crazy Available only in ...   
1                            Ok lar Joking wif u oni   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3        U dun say so early hor U c already then say   
4  Nah I dont think he goes to usf he lives aroun...   

                                              Tokens  
0  [Go, until, jurong, point, crazy, Available, o...  
1                     [Ok, lar, Joking, wif, u, oni]  
2  [Free, entry, in, 2, a, wkly, comp, to, win, F...  
3  [U, dun, say, so, early, hor, U, c, already, t...  
4  [Nah, I, dont, think, he, goes, to, usf, he, l...

In [10]:
stpwrds = nltk.corpus.stopwords.words("english")
stpwrds[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [11]:
def remove_stpwrds(text):
    text = [word for word in text if word not in stpwrds]
    return text

In [12]:
Data['Stp_Wrds'] = Data['Tokens'].apply(lambda x: remove_stpwrds(x))
Data.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                            rm_punct  \
0  Go until jurong point crazy Available only in ...   
1                            Ok lar Joking wif u oni   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3        U dun say so early hor U c already then say   
4  Nah I dont think he goes to usf he lives aroun...   

                                              Tokens  \
0  [Go, until, jurong, point, crazy, Available, o...   
1                     [Ok, lar, Joking, wif, u, oni]   
2  [Free, entry, in, 2, a, wkly, comp, to, win, F...   
3  [U, dun, say, so, early, hor, U, c, already, t...   
4  [Nah, I, dont, think, he, goes, to, usf, he, l...   

                                            Stp_Wrds  
0  [Go, jurong, point, crazy, Available, bugis, n...  
1                     [Ok, lar, Joking, wif, u, oni]  
2  [Free, entry, 2, wkly, comp, win, FA, Cup, fin...  
3      [U, dun, say, early, hor, U, c, already, say]  
4  [Nah, I, dont, think, goes, usf, lives, around...

In [13]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [14]:
def stemming(text):
    text = [ps.stem(word) for word in text]
    return text

In [15]:
Data['Stem'] = Data['Stp_Wrds'].apply(lambda x: stemming(x))
Data.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                            rm_punct  \
0  Go until jurong point crazy Available only in ...   
1                            Ok lar Joking wif u oni   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3        U dun say so early hor U c already then say   
4  Nah I dont think he goes to usf he lives aroun...   

                                              Tokens  \
0  [Go, until, jurong, point, crazy, Available, o...   
1                     [Ok, lar, Joking, wif, u, oni]   
2  [Free, entry, in, 2, a, wkly, comp, to, win, F...   
3  [U, dun, say, so, early, hor, U, c, already, t...   
4  [Nah, I, dont, think, he, goes, to, usf, he, l...   

                                            Stp_Wrds  \
0  [Go, jurong, point, crazy, Available, bugis, n...   
1                     [Ok, lar, Joking, wif, u, oni]   
2  [Free, entry, 2, wkly, comp, win, FA, Cup, fin...   
3      [U, dun, say, early, hor, U, c, already, say]   
4  [Nah, I, dont, think, goes, usf, lives, around...   

                                                Stem  
0  [Go, jurong, point, crazi, avail, bugi, n, gre...  
1                       [Ok, lar, joke, wif, u, oni]  
2  [free, entri, 2, wkli, comp, win, FA, cup, fin...  
3      [U, dun, say, earli, hor, U, c, alreadi, say]  
4  [nah, I, dont, think, goe, usf, live, around, ...

In [16]:
wn = nltk.WordNetLemmatizer()

In [17]:
def lemmatize(text):
    text = [wn.lemmatize(word) for word in text]
    return text

In [18]:
Data['Lemmatize'] = Data['Stp_Wrds'].apply(lambda x: lemmatize(x))
Data.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                            rm_punct  \
0  Go until jurong point crazy Available only in ...   
1                            Ok lar Joking wif u oni   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3        U dun say so early hor U c already then say   
4  Nah I dont think he goes to usf he lives aroun...   

                                              Tokens  \
0  [Go, until, jurong, point, crazy, Available, o...   
1                     [Ok, lar, Joking, wif, u, oni]   
2  [Free, entry, in, 2, a, wkly, comp, to, win, F...   
3  [U, dun, say, so, early, hor, U, c, already, t...   
4  [Nah, I, dont, think, he, goes, to, usf, he, l...   

                                            Stp_Wrds  \
0  [Go, jurong, point, crazy, Available, bugis, n...   
1                     [Ok, lar, Joking, wif, u, oni]   
2  [Free, entry, 2, wkly, comp, win, FA, Cup, fin...   
3      [U, dun, say, early, hor, U, c, already, say]   
4  [Nah, I, dont, think, goes, usf, lives, around...   

                                                Stem  \
0  [Go, jurong, point, crazi, avail, bugi, n, gre...   
1                       [Ok, lar, joke, wif, u, oni]   
2  [free, entri, 2, wkli, comp, win, FA, cup, fin...   
3      [U, dun, say, earli, hor, U, c, alreadi, say]   
4  [nah, I, dont, think, goe, usf, live, around, ...   

                                           Lemmatize  
0  [Go, jurong, point, crazy, Available, bugis, n...  
1                     [Ok, lar, Joking, wif, u, oni]  
2  [Free, entry, 2, wkly, comp, win, FA, Cup, fin...  
3      [U, dun, say, early, hor, U, c, already, say]  
4  [Nah, I, dont, think, go, usf, life, around, t...

In [19]:
Data = Data.drop(['rm_punct','Tokens','Stp_Wrds','Stem'], axis = 1)

In [20]:
Data.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                           Lemmatize  
0  [Go, jurong, point, crazy, Available, bugis, n...  
1                     [Ok, lar, Joking, wif, u, oni]  
2  [Free, entry, 2, wkly, comp, win, FA, Cup, fin...  
3      [U, dun, say, early, hor, U, c, already, say]  
4  [Nah, I, dont, think, go, usf, life, around, t...

In [21]:
def clean_data(text):
    text = [word for word in text]
    return " ".join(text)

In [22]:
Data['Clean'] = Data['Lemmatize'].apply(lambda x: clean_data(x))
Data.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                           Lemmatize  \
0  [Go, jurong, point, crazy, Available, bugis, n...   
1                     [Ok, lar, Joking, wif, u, oni]   
2  [Free, entry, 2, wkly, comp, win, FA, Cup, fin...   
3      [U, dun, say, early, hor, U, c, already, say]   
4  [Nah, I, dont, think, go, usf, life, around, t...   

                                               Clean  
0  Go jurong point crazy Available bugis n great ...  
1                            Ok lar Joking wif u oni  
2  Free entry 2 wkly comp win FA Cup final tkts 2...  
3                U dun say early hor U c already say  
4         Nah I dont think go usf life around though

In [23]:
Data = Data.drop(['Lemmatize'], axis = 1)
Data.head()

label                                            message  \
0   ham  Go until jurong point, crazy.. Available only ...   
1   ham                      Ok lar... Joking wif u oni...   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   
3   ham  U dun say so early hor... U c already then say...   
4   ham  Nah I don't think he goes to usf, he lives aro...   

                                               Clean  
0  Go jurong point crazy Available bugis n great ...  
1                            Ok lar Joking wif u oni  
2  Free entry 2 wkly comp win FA Cup final tkts 2...  
3                U dun say early hor U c already say  
4         Nah I dont think go usf life around though

In [24]:
Data = pd.get_dummies(Data, columns = ['label'])
Data.head()

message  \
0  Go until jurong point, crazy.. Available only ...   
1                      Ok lar... Joking wif u oni...   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3  U dun say so early hor... U c already then say...   
4  Nah I don't think he goes to usf, he lives aro...   

                                               Clean  label_ham  label_spam  
0  Go jurong point crazy Available bugis n great ...          1           0  
1                            Ok lar Joking wif u oni          1           0  
2  Free entry 2 wkly comp win FA Cup final tkts 2...          0           1  
3                U dun say early hor U c already say          1           0  
4         Nah I dont think go usf life around though          1           0

In [25]:
Data = Data.drop(['label_spam'], axis = 1)
Data.head()

message  \
0  Go until jurong point, crazy.. Available only ...   
1                      Ok lar... Joking wif u oni...   
2  Free entry in 2 a wkly comp to win FA Cup fina...   
3  U dun say so early hor... U c already then say...   
4  Nah I don't think he goes to usf, he lives aro...   

                                               Clean  label_ham  
0  Go jurong point crazy Available bugis n great ...          1  
1                            Ok lar Joking wif u oni          1  
2  Free entry 2 wkly comp win FA Cup final tkts 2...          0  
3                U dun say early hor U c already say          1  
4         Nah I dont think go usf life around though          1

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()
x = count_vector.fit_transform(Data['Clean'])
print(x.shape)

(5572, 9133)


In [27]:
print(x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [28]:
SMSData = pd.DataFrame(x.toarray(), columns = count_vector.get_feature_names())
SMSData.head()

008704050406  0089my  0121  01223585236  01223585334  0125698789  02  \
0             0       0     0            0            0           0   0   
1             0       0     0            0            0           0   0   
2             0       0     0            0            0           0   0   
3             0       0     0            0            0           0   0   
4             0       0     0            0            0           0   0   

   020603  0207  02070836089  ...  zero  zhong  zindgi  zoe  zogtorius  zoom  \
0       0     0            0  ...     0      0       0    0          0     0   
1       0     0            0  ...     0      0       0    0          0     0   
2       0     0            0  ...     0      0       0    0          0     0   
3       0     0            0  ...     0      0       0    0          0     0   
4       0     0            0  ...     0      0       0    0          0     0   

   zouk  zyada  üll  〨ud  
0     0      0    0    0  
1     0      0    0    0  
2     0      0    0    0  
3     0      0    0    0  
4     0      0    0    0  

[5 rows x 9133 columns]

In [29]:
SMSData['label'] = Data['label_ham']
SMSData.head()

008704050406  0089my  0121  01223585236  01223585334  0125698789  02  \
0             0       0     0            0            0           0   0   
1             0       0     0            0            0           0   0   
2             0       0     0            0            0           0   0   
3             0       0     0            0            0           0   0   
4             0       0     0            0            0           0   0   

   020603  0207  02070836089  ...  zhong  zindgi  zoe  zogtorius  zoom  zouk  \
0       0     0            0  ...      0       0    0          0     0     0   
1       0     0            0  ...      0       0    0          0     0     0   
2       0     0            0  ...      0       0    0          0     0     0   
3       0     0            0  ...      0       0    0          0     0     0   
4       0     0            0  ...      0       0    0          0     0     0   

   zyada  üll  〨ud  label  
0      0    0    0      1  
1      0    0    0      1  
2      0    0    0      0  
3      0    0    0      1  
4      0    0    0      1  

[5 rows x 9134 columns]

# Algorithm

## Logistic Regression 

In [30]:
#Logistic Regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = SMSData.drop(['label'], axis = 1)
y = SMSData.label

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [31]:
logit_model = LogisticRegression()
logit_model.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
pred = logit_model.predict(x_test)

In [33]:
#Evaluation

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
print("Accuracy:", metrics.accuracy_score(y_test, pred))

[[ 190   31]
 [   1 1450]]
              precision    recall  f1-score   support

           0       0.99      0.86      0.92       221
           1       0.98      1.00      0.99      1451

    accuracy                           0.98      1672
   macro avg       0.99      0.93      0.96      1672
weighted avg       0.98      0.98      0.98      1672

Accuracy: 0.9808612440191388


## Random Forest 

In [34]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier()
classifier.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [35]:
y_pred = classifier.predict(x_test)

In [36]:
#Evaluation

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[[ 179   42]
 [   0 1451]]
              precision    recall  f1-score   support

           0       1.00      0.81      0.90       221
           1       0.97      1.00      0.99      1451

    accuracy                           0.97      1672
   macro avg       0.99      0.90      0.94      1672
weighted avg       0.98      0.97      0.97      1672

Accuracy: 0.9748803827751196


## KNN Algorithm

In [37]:
from sklearn.neighbors import KNeighborsClassifier
kclassifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p =2)
kclassifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [38]:
predictions = kclassifier.predict(x_test)

In [39]:
#Evaluation

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))
print("Accuracy:", metrics.accuracy_score(y_test, predictions))

[[  72  149]
 [   0 1451]]
              precision    recall  f1-score   support

           0       1.00      0.33      0.49       221
           1       0.91      1.00      0.95      1451

    accuracy                           0.91      1672
   macro avg       0.95      0.66      0.72      1672
weighted avg       0.92      0.91      0.89      1672

Accuracy: 0.9108851674641149


## SVM Algorithm

In [40]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [41]:
ypred = model.predict(x_test)

In [42]:
#Evaluation

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test, ypred))
print(classification_report(y_test, ypred))
print("Accuracy:", metrics.accuracy_score(y_test, ypred))

[[   0  221]
 [   0 1451]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       221
           1       0.87      1.00      0.93      1451

    accuracy                           0.87      1672
   macro avg       0.43      0.50      0.46      1672
weighted avg       0.75      0.87      0.81      1672

Accuracy: 0.867822966507177


C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [43]:
svcclassifier = SVC(kernel = 'linear')
svcclassifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [44]:
predict1 = svcclassifier.predict(x_test)

In [45]:
print(confusion_matrix(y_test, predict1))
print(classification_report(y_test, predict1))
print("Accuracy:", metrics.accuracy_score(y_test, predict1))

[[ 193   28]
 [   3 1448]]
              precision    recall  f1-score   support

           0       0.98      0.87      0.93       221
           1       0.98      1.00      0.99      1451

    accuracy                           0.98      1672
   macro avg       0.98      0.94      0.96      1672
weighted avg       0.98      0.98      0.98      1672

Accuracy: 0.9814593301435407


In [46]:
svclassifier = SVC(kernel = 'poly', degree = 8)
svclassifier.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [47]:
predict2 = svclassifier.predict(x_test)

In [48]:
print(confusion_matrix(y_test, predict2))
print(classification_report(y_test, predict2))
print("Accuracy:", metrics.accuracy_score(y_test, predict2))

[[   0  221]
 [   0 1451]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       221
           1       0.87      1.00      0.93      1451

    accuracy                           0.87      1672
   macro avg       0.43      0.50      0.46      1672
weighted avg       0.75      0.87      0.81      1672

Accuracy: 0.867822966507177


C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [49]:
svclassifier1 = SVC(kernel = 'sigmoid')
svclassifier1.fit(x_train,  y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [50]:
predict3 = svclassifier1.predict(x_test)

In [51]:
print(confusion_matrix(y_test, predict3))
print(classification_report(y_test, predict3))
print("Accuracy:", metrics.accuracy_score(y_test, predict3))

[[   0  221]
 [   0 1451]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       221
           1       0.87      1.00      0.93      1451

    accuracy                           0.87      1672
   macro avg       0.43      0.50      0.46      1672
weighted avg       0.75      0.87      0.81      1672

Accuracy: 0.867822966507177


C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# SVM (linear) model is the best fit model for spam ham classification